
Exception caught at 2025-10-20 14:48:54.966942:
Traceback (most recent call last):
  File "internal/snthpy/synthesis.py", line 89, in <module>
    main(args)
  File "internal/snthpy/synthesis.py", line 34, in main
    config_parameters, env = config_parser.read_config(args.config)
  File "/home/shanen/CPRE 3810 Project 1/Project_Part_1/internal/snthpy/config_parser.py", line 69, in read_config
    rars_tok = json.loads(c.get(config, "rars_token"))
  File "/usr/local/mentor/calibre/pkgs/icv_python/asp/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/local/mentor/calibre/pkgs/icv_python/asp/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/local/mentor/calibre/pkgs/icv_python/asp/lib/python3.8/configparser.py", line 434, in _interpolate_some
    raise InterpolationMissingOptionError(
configparser.InterpolationMissingOptionError: Bad value substitution: option 'rars_token' in section 'Lab' contains an interpolation key 'rars_p_tok' which is not a valid option name. Raw value: '%(RARS_P_TOK)s'
